name: movie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  another_flutter_splash_screen: ^1.1.4
  cached_network_image: ^3.2.3
  camera: ^0.10.4
  image_picker: ^0.8.7+4
  flutter_otp_text_field: ^1.1.1
  http: ^0.13.4
  flutter_dialogs: ^3.0.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi_web: ^0.3.5+1
  shared_preferences: ^2.1.2
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: FontAmarante
      fonts:
        - asset: assets/fonts/Amarante-Reguler.ttf